In [1]:
import numpy as np

In [3]:
W1 = np.random.randn(3, 2) * 0.1
W1

array([[-0.05538772,  0.09824388],
       [ 0.037946  , -0.09706523],
       [-0.02515485, -0.00903055]])

In [11]:
X = np.random.randn(100, 2)
X.T

array([[-1.16872578,  0.84172555, -1.6260802 , -0.14838253, -0.27450975,
         0.73409929, -1.24204526,  0.00671926,  1.34653274, -0.09371296,
        -1.05039233, -1.05302781,  0.38322318,  0.44712656, -0.51347119,
         0.12047707,  0.22436354,  0.79081062,  0.66406453, -0.80355511,
         0.23356261,  0.87806275, -0.00768021, -2.07972079,  0.10117019,
        -0.44821784, -1.0911717 ,  1.29474847, -0.37263569,  1.32096606,
         0.19644555,  1.91482708,  1.76963719,  0.93401414, -0.40928079,
         0.04479149, -0.57197003, -0.67670551,  0.36116992,  1.88212065,
         0.89383048, -0.09696701,  0.63968676,  0.27468316, -0.90283224,
         0.98235329, -1.4443301 , -0.2952589 ,  0.05088756, -0.6639924 ,
         1.96492232,  1.48878257, -0.61854126,  0.46477266,  1.85030186,
        -0.73498426,  0.06443774, -0.98285909, -1.18010103, -0.57746279,
        -0.69161295, -1.90262737,  0.58804318, -0.04938039,  1.20885494,
         0.31053257,  0.95480675,  0.3146105 ,  0.6

In [35]:
s = W1 @ X.T

W2 = np.random.randn(1, 3) * 0.1
y = ((X[:, 0] ** 2 + X[:, 1] ** 2 > 1).astype(int) * 2 - 1).reshape(1, -1)

W2 @ (W1 @ X.T)

array([[ 1.34855652e-02, -1.91923007e-03,  9.57822671e-03,
        -9.51305995e-04,  2.20224695e-03, -9.13440287e-03,
         6.90498643e-03, -2.26489563e-03, -1.31458690e-02,
         2.83736700e-04,  7.60776710e-03,  8.24449287e-03,
        -9.18773320e-03, -4.89154578e-03,  5.43803402e-03,
        -1.60840857e-03,  2.75631786e-03, -2.91349939e-03,
         5.44597899e-04, -3.39379262e-04, -3.32526072e-03,
        -5.10203571e-03,  4.40910663e-04,  1.08527376e-02,
        -7.49401698e-03,  1.08708105e-02,  9.26838645e-03,
        -1.04350531e-02,  3.24438794e-03, -8.89576256e-03,
        -1.46843872e-03, -1.05811644e-02, -9.69988420e-03,
        -5.09098185e-03,  2.86091239e-03, -1.09548690e-02,
         5.22692585e-03, -1.70899756e-03, -5.12708742e-03,
        -1.19803933e-02, -3.27290622e-03,  2.09235843e-03,
        -2.23294704e-03,  4.36558094e-04,  3.80800573e-03,
        -7.91345784e-03,  4.67447170e-03,  3.15471415e-03,
        -6.69476729e-04,  5.75167337e-03, -1.25136153e-0